[workspace]

members = [
    "proto-build",
    "cosmos-sdk-proto",
    "cosmos-tx"
]

[patch.crates-io]
tonic = { git = "https://github.com/boxdot/tonic", rev = "38817a9" }
# h2 = { git = "https://github.com/boxdot/h2", rev = "f6ae28c3" }